hyperium/hyperium.github.io

- index.html
The documentation button was leading to a 404 when accessing through http://hyper.rs.
This commit points the button to the same link used on the Documentation found on the navbar.
> Updates the broken link on the Documentation button

- _guides/client/basic.md
The previous version was not beginner friendly and would lead to the ```Can't find crate``` error.
> Add dependencies to be included in Cargo.toml

- _guides/client/json.md
The example uses Deref coercions, not AsRef.
> AsRef -> Deref

- _guides/server/echo.md
I like the minimalist approach of these articles, but I think a bit too much is omitted, even if the reader may figure this out themselves through error messages.
I would add that:
* `HelloWorld` is to be replaced by `Echo` in the `.bind()` call in `main`.
* `hyper::Body` needs to be imported
* `futures::future::FutureResult` needs to be imported
* Setting `Response = Response<Map<Body…` will break the `GET /` match in the intermediate stage of the code/article; `// only this match arm needs to change` suggests otherwise.
The bottom example doesn't compile for me, as `use futures::stream::Map` and `use futures::future::Map` clash, and disabling one or the other doesn't work either.
> Minor edits

- _guides/server/hello-world.md
- _includes/head.html
Changes to hello-world server example to add dependencies step, as well as adding the Rust favicon.
Hopefully takes care of [#1289](https://github.com/hyperium/hyper/issues/1289) and [#1288](https://github.com/hyperium/hyper/issues/1288).
> feat(server/hello-world): add dependencies step; also add favicon to website

- .travis.sh
- _guides/server/handle_post.md
- _guides/server/response_strategies.md
Here are a couple server guide pages to go with the examples I recently contributed. It wasn't clear to me how to add them to the table of contents on the guide pages. Am I missing something, or is it automatic?
The last section of response_strategies.md, on building the server, feels weak to me. I'm not very familiar with the working of tokio, so a close reading there would be appreciated.
I think a final page about tying it all together is needed. I kept the file serving and web api examples separate because I found needed type conversions when they were combined obscured the main point of the examples. Adding in Post handling will add further conversions. I suspect that in moderately complex applications, the cleanest approach will be to define wrapper structs for Service::Response and …
> Add guides for handling posts and complex responses

- _config.yml
- _guides/index.md
- _guides/server/echo.md
- _guides/server/handle_post.md
- _guides/server/response_strategies.md
While reading the guides, I noticed that multiple links were broken. As @adrian5 pointed out in #15, the link to the *Hello, world!* example on the [*Echo, echo, echo* page](https://hyper.rs/guides/server/echo/index) directs to [itself](https://hyper.rs/guides/server/echo/index) rather than the actual [*Hello, world!* page](https://hyper.rs/guides/server/hello-world/). Multiple more links are affected as well.
First, I wanted to fix this by prefixing all URLs with `../`. This would fix the HTMLs links generated by Jekyll. But as @jolhoeft objected in #24, this would break all links when reading the Markdown files on github.com.
Both problems are solved by using the [Jekyll Relative Links plug-in][1] and directly linking to the Markdown files with their `.md` extension. With this plug-in, …
> Fix broken links with Jekyll Relative Links

- _guides/server/handle_post.md
Update link from pointing to a copy of params.rs on `master` to pointing to a copy of params.rs on `tag 0.11.25`. This is intended to help those following along with the guides to be able to compile code using the latest version of hyper pulled down from crates.io
> Update link to params.rs

- _guides/server/hello-world.md
I hope it's alright to make a PR without first making an issue for it.  Normally I would, but this is just a little typo fix so I figured it probably doesn't matter.
> fix a typo `a` -> `are`

- _guides/server/echo.md
I went through the Hyper 0.12 guide today and hit this snag.
The example wants to call `futures::future::ok`, but imports `futures::Future` instead of `futures::future`. The former is a type, which collides with a type imported in the previous guide and the latter is a module containing the function we want.
> Fix casing on 'echo' guide

- _guides/server/hello-world.md
I suppose the doc link to [Service](https://docs.rs/hyper/0.12.33/hyper/service/trait.Service.html) trait should be updated to point to `/hyper/service/trait.Service.html` instead of `/hyper/trait.Service.html`.
> Update doc link to Service trait

- _guides/client/advanced.md
A user who goes through the client tutorials step-by-step will end up with code that doesn't compile because there are some imports missing. This adds the missing imports so that the code will compile and run.
> Added missing imports to advanced client documentation

- _guides/client/advanced.md
Both of these links are broken in the published version: https://hyper.rs/guides/client/advanced/
> Fix a pair of broken links in the Advanced Client Usage guide

- _layouts/home.html
Very minor but noticed that the link to TechEmpower was from Round 15 where the most recent version is Round 18. Hyper is in position 1 for Round 18 plaintext so it seems suitable for the argument being made about Hyper's speed.
> Update *Blazing fast* link to newest TechEmpower round

- _guides/client/advanced.md
Previously `}` was used instead of `]` at the end of the displayed feature list.
> Fixed typo in advanced guide Cargo.toml example

- _guides/client/basic.md
- _guides/client/configuration.md
While reading the client documentation I noticed that attempting to follow the links for [`hyper::Client`](https://docs.rs/hyper/0.13.1/hyper/struct.Client.html) on the [basic](https://hyper.rs/guides/client/basic/) and [configuration](https://hyper.rs/guides/client/configuration/) pages results in an error that says _"The requested resource does not exist"_
If you attempt to fetch the page, you get a **404** error.
```shell
[12:39:39] tucker@oryoki:~ § url='https://docs.rs/hyper/0.13.1/hyper/struct.Client.html'
[12:39:40] tucker@oryoki:~ § curl --silent --head --fail $url                                           
curl: (22) The requested URL returned error: 404
```
If you add the full path to [`hyper::client::Client`](https://docs.rs/hyper/0.13.1/hyper/client/struct.Client.html), then …
> Fix hyper::Client links

- _includes/footer.html
To allow for easier editing of pages by the community, adds a link to all pages
(using _includes/footer.html) that links to the corresponding file in the
GitHub repo.
Fixes https://github.com/hyperium/hyper/issues/2131.
> Add link to edit on GitHub

- _guides/client/basic.md
The tokio site changed their document path.
> Update the broken Tokio documentation link

- _guides/client/basic.md
Changes `resp` to be mutable in the first example too so the code matches the one below. Following the tutorial I got an error, because the second code sample was subtly different.
> Make basic guide code more consistent to avoid errors

- _config.yml
- _stable/client/basic.md
- _stable/client/index.md
This add the first of the `client` 1.0 guides.
Addresses https://github.com/hyperium/hyper/issues/3098
> feat: add 1.0 version of basic client guide

- _legacy/server/echo.md
- _stable/server/echo.md
> teach checking for limits on request bodies

- .github/workflows/contrib.yml
- _contrib/contributing.md
- _contrib/governance.md
- _contrib/issues.md
- _contrib/tenets.md
A few links were broken by not having their underscores replaced with hyphens, meaning they weren't matching the filenames. This change makes sure all internal link underscores are replaced with hyphens, and the first PR that applies the updated script is included.
> feat: fix broken links

- .github/workflows/contrib.yml
This should fix the last of the broken links. I didn't include the bot PR in this since I think it's a good opportunity to see it in action on the main repo. But to see that this fix is correct, here is the PR in my fork: https://github.com/oddgrd/hyperium.github.io/pull/6/files
> ci: fix broken links to contributing

- .github/workflows/check_guides.sh
- _config.yml
- _stable/client/basic.md
- _stable/index.md
- _stable/server/hello-world.md
Congrats on the release, one step closer :partying_face:. I saw you added the legacy client to hyper-util as well, should we use it in the advanced guide: https://github.com/hyperium/hyperium.github.io/pull/77? The sending of requests in parallel part could be made a lot simpler with the legacy client (and it may not be correct currently :sweat_smile:).
> chore: v1.0.0-rc.3

- .github/workflows/contrib.yml
- _includes/footer.html
Populate a new page field 'hyper_path' for copied contrib files. Conditionally link back to [hyper](https://github.com/hyperium/hyper) if a 'hyper_path' is present, otherwise continue to reference [hyperium.github.io](https://github.com/hyperium/hyperium.github.io) (relevant for all collections besides contrib).
Addresses hyperium/hyper#3210
There are several interesting manipulations that happen within [contrib.yml](https://github.com/hyperium/hyperium.github.io/blob/da1d0e45d37042f637102fdf5fa5cbae23973737/.github/workflows/contrib.yml). These new additions should account for files that are:
- renamed <sm>(README -> index)</sm>
- copied / moved <sm>(CONTRIBUTING -> docs/contributing)</sm>
- in a separate repository (specifically [hyper](https://github.com/hyperium/hyper))
I've been …
> chore(site): edit GitHub links (#3210)

- .github/workflows/check_guides.sh
- _config.yml
- _stable/client/basic.md
- _stable/index.md
- _stable/server/hello-world.md
Hey! This just updates hyper to rc4 and http-body-util to rc3, and it changes the guides to use the new hyper io traits from hyper-util via a git dependency. Tests pass locally.
Also congrats on going full-time open-source, that's very exciting news! :partying_face:
> chore: update hyper crates, use hyper io traits

- _stable/client/basic.md
`chunk` seems to be a reference already, and `tokio`'s `stdout` is used as `io::stdout` not being imported directly.
> guide: update basic client guide

- _stable/client/basic.md
There is no "TCP handshake" happening in that call.
> Fix comment

- _stable/init/runtime.md
part of https://github.com/hyperium/hyper/issues/3411
This PR adds a guide for `hyper::rt` which includes both a simple implementation and hyper_util's implementation
> guide: add rt guide

- _data/stable.yml
This PR allows `runtime` to show in the navigation bar
https://hyper.rs/guides/1/init/runtime/
> guide: add runtime to _data

- .github/workflows/check_guides.sh
- _config.yml
- _data/stable.yml
- _stable/server/middleware.md
- _stable/upgrading.md
Add middleware doc after hyper not dependents on the tower crate.
Related discussion: https://github.com/hyperium/hyper/issues/3154
> add middleware doc for server

- _config.yml
- _stable/server/hello-world.md
fixes https://github.com/hyperium/hyperium.github.io/issues/132
> fix: docs url

- _layouts/guide.html
- _stable/client/basic.md
- _stable/index.md
The links in the "Getting Started" page are broken: https://hyper.rs/guides/1/
This fixes them:
It also fixes some other instances of broken links, for example `Request` on this page: https://hyper.rs/guides/1/client/basic/#setup
> Fix broken links

- _stable/client/basic.md
This pull request includes a small change to the `_stable/client/basic.md` file. The change updates the URLs for the `Response` and `Request` references to point to the correct documentation pages.
Documentation updates:
* [`_stable/client/basic.md`](diffhunk://#diff-5b94a577a3e6091b2b9fa1a858cbb66782fc679a15d5af646c03702fc0978b83L240-R241): Updated the URLs for `Response` and `Request` references to point to the correct HTTP documentation pages.
> Fix the missing url in basic.md

- _stable/server/graceful-shutdown.md
Need to drop the listener for the graceful shutdown to fully succeed. Otherwise, even though we cannot `curl` the server addr, `netstat` still shows the process listening. This will align the example with the hyper-util example in: https://github.com/hyperium/hyper-util/blob/e74ab7888638e768de17c47ed5f20c8b623a308f/examples/server_graceful.rs#L47
> fix example in graceful-shutdown.md: add `drop(listener)`
